#!/bin/sh

if [ $# != 2 ]; then
  echo 1>&2 "USAGE: bumpversion <versionfile> <changelog>"
  exit 1
fi

version="$(cat "$1")"
echo "wollmux (${version}-0lhm1) tramp; urgency=low

    * Version bump.

 -- Felix WollMux <wollmux-general@lists.forge.osor.eu>  Mon, 23 May 2011 19:35:16 +0200
" >"$2"
