#!/bin/sh

if [ $# != 2 ]; then
  echo 1>&2 "USAGE: bumpversion <versionfile> <changelog>"
  exit 1
fi

version="$(cat "$1")"
echo "wollmux (${version}-0lhm1) halut; urgency=low

    * Version bump.

 -- Felix WollMux <wollmux-general@lists.forge.osor.eu>  Wed, 06 Jul 2007 16:13:16 +0200
" >"$2"
