#!/bin/sh

if [ $# != 4 ]; then
  echo 1>&2 "USAGE: makeversion <versionfile> <buildinfofile> <descriptionxmlfile> <updatexmlfile>"
  exit 1
fi

# check if <versionfile> contains "rev", if not we use the version number from <versionfile>
if [ -e "$1" ]; then
  version=$(head -n 1 "$1")
  echo "$version" >"$1" 
  echo "Version: $version" >"$2"
fi


cat >"$3" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<description xmlns="http://openoffice.org/extensions/description/2006"
             xmlns:xlink="http://www.w3.org/1999/xlink">
        <version value="$version" />
        <identifier value="de.muenchen.allg.d101.wollmux"/>
        <dependencies>
                <OpenOffice.org-minimal-version value="2.1" name="OpenOffice.org 2.1"/>
        </dependencies>

        <publisher>
                <name xlink:href="http://www.wollmux.org" lang="de">WollMux.org</name>
        </publisher>

        <display-name>
                <name lang="de-DE">WollMux</name>
        </display-name>

        <update-information>
          <src xlink:href="http://limux.tvc.muenchen.de/ablage/sonstiges/wollmux/packages/WollMux-snapshot/WollMux.update.xml"/>
        </update-information>
<!--    <registration>
                <simple-license accept-by="admin" default-license-id="en-NZ" suppress-on-update="true" >
                        <license-text xlink:href="registration/license_de-DE.txt" lang="de-DE" />
                        <license-text xlink:href="registration/license_en-GB.txt" lang="en-GB" />
                        <license-text xlink:href="registration/license_en-NZ.txt" lang="en-NZ" license-id="en-NZ" />
                        <license-text xlink:href="registration/license_en-US.txt" lang="en-US" />
                </simple-license>
        </registration>
-->
</description>
EOF

cat >"$4" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<description xmlns="http://openoffice.org/extensions/update/2006"
	     xmlns:xlink="http://www.w3.org/1999/xlink">
	<version value="$version" />
	<identifier value="de.muenchen.allg.d101.wollmux"/>
	<update-download>
          <src xlink:href="http://limux.tvc.muenchen.de/ablage/sonstiges/wollmux/packages/WollMux-snapshot/WollMux.oxt"/>
	</update-download>
</description>
EOF
