#!/bin/sh

if [ $# != 4 ]; then
  echo 1>&2 "USAGE: makeversion <versionfile> <buildinfofile> <descriptionxmlfile> <updatexmlfile>"
  echo 1>&2 "If <versionfile> exists and contains a version number that does not contain 'rev'"
  echo 1>&2 "the version number from <versionfile> is used."
  exit 1
fi

#date=$(LC_ALL=C svn info|grep "^Last Changed Date"|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
#rev=$(LC_ALL=C svn info|grep "^Revision"|sed -n 's/.* \([0-9]\+\).*/\1/p')
#if [ -z "$date" ]; then
#  echo 1>&2 "Getting SVN version info failed => Trying GIT"
#  date=$(git log -1 --date=short|grep ^Date:|head -n 1|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
#  rev=$(git log -1 --date=short|sed -n 's/^commit \(.*\)/\1/p'|head -n 1)
#  if [ -z "$date" ]; then
#    echo 1>&2 "Getting GIT version info failed => Trying HG"
    date=$(hg log -l 1 --style=compact|head -n 1|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
    rev=$( hg log -l 1 --style=compact|head -n 1|sed 's/^.*\([0-9a-zA-Z]\{12,12\}\).*$/\1/')
    localrev=$(hg log -l 1 --style=compact|head -n 1|cut -d "[" -f 1)
    test -z "$date" && echo 1>&2 "Getting HG version info failed => Falling back to shipped version info"
#  fi
#fi

test -z "$date" && exit 1
test -z "$rev" && exit 1

v1=$((${date%%-*} - 2000))
v2=$(echo $date| sed 's/[^-]*-0\?\([^-]*\)-.*/\1/')
#v3=$(( $(echo ${date##*-}| sed 's/^0\?\(.*\)/\1/') / 10 ))

version="$v1.${v2}rev$localrev"

#if [ -e "$1" ]; then
#  dotversion=$(sed -n "s/^$version//p" "$1")
#  version=${version}${dotversion}
#fi

# check if <versionfile> contains "rev", if not we use the version number from <versionfile>
if [ -e "$1" ]; then
  head -n 1 "$1"|grep -q "rev"
  if [ $? -ne 0 ]; then
    version=$(head -n 1 "$1")
  fi
fi

echo "$version" >"$1" 
echo "Version: $version, Revision: $rev" >"$2"

cat >"$3" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<description xmlns="http://openoffice.org/extensions/description/2006"
	     xmlns:xlink="http://www.w3.org/1999/xlink">
	<version value="$version" />
	<identifier value="de.muenchen.allg.d101.wollmux"/>
	<dependencies>
		<OpenOffice.org-minimal-version value="2.1" name="OpenOffice.org 2.1"/>
	</dependencies>

	<publisher>
		<name xlink:href="http://www.wollmux.org" lang="de">WollMux.org</name>
	</publisher>

	<display-name>
		<name lang="de-DE">WollMux</name>
	</display-name>

	<update-information>
	  <src xlink:href="http://limux.tvc.muenchen.de/ablage/sonstiges/wollmux/packages/WollMux-snapshot/WollMux.update.xml"/>
	</update-information>
<!--	<registration>
		<simple-license accept-by="admin" default-license-id="en-NZ" suppress-on-update="true" >
			<license-text xlink:href="registration/license_de-DE.txt" lang="de-DE" />
			<license-text xlink:href="registration/license_en-GB.txt" lang="en-GB" />
			<license-text xlink:href="registration/license_en-NZ.txt" lang="en-NZ" license-id="en-NZ" />
			<license-text xlink:href="registration/license_en-US.txt" lang="en-US" />
		</simple-license>
	</registration>
-->
</description>
EOF

cat >"$4" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<description xmlns="http://openoffice.org/extensions/update/2006"
	     xmlns:xlink="http://www.w3.org/1999/xlink">
	<version value="$version" />
	<identifier value="de.muenchen.allg.d101.wollmux"/>
	<update-download>
          <src xlink:href="http://limux.tvc.muenchen.de/ablage/sonstiges/wollmux/packages/WollMux-snapshot/WollMux.oxt"/>
	</update-download>
</description>
EOF
