#!/bin/sh

if [ $# != 3 ]; then
  echo 1>&2 "USAGE: makeversion <versionfile> <buildinfofile> <changelog>"
  exit 1
fi

date=$(LC_ALL=C svn info|grep "^Last Changed Date"|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
rev=$(LC_ALL=C svn info|grep "^Revision"|sed -n 's/.* \([0-9]\+\).*/\1/p')
if [ -z "$date" ]; then
  echo 1>&2 "Getting SVN version info failed => Trying GIT"
  date=$(git log -1 --date=short|grep ^Date:|head -n 1|sed -n 's/.*\([0-9]\{4\}-[0-9][0-9]-[0-9][0-9]\).*/\1/p')
  rev=$(git log -1 --date=short|sed -n 's/^commit \(.*\)/\1/p'|head -n 1)
  test -z "$date" && echo 1>&2 "Getting GIT version info failed => Falling back to shipped version info"
fi
test -z "$date" && exit 1
test -z "$rev" && exit 1

v1=$((${date%%-*} - 2004))
v2=$(echo $date| sed 's/[^-]*-0\?\([^-]*\)-.*/\1/')
v3=$(( $(echo ${date##*-}| sed 's/[^-]*-0\?\([^-]*\)-.*/\1/') / 10 ))

echo "$v1.$v2.$v3" >"$1" 
echo "Version: $v1.$v2.$v3, Revision: $rev" >"$2"
echo "wollmux ($v1.$v2.$v3) halut; urgency=low

    * Version bump.

 -- Felix WollMux <wollmux-general@lists.forge.osor.eu>  Wed, 06 Jul 2007 16:13:16 +0200
" >"$3"
#echo "$(($(date +%Y) - 2004)).$(date +%m|sed s/^0//).$(($(date +%d|sed s/^0//) / 10))"
