/*
 * Dateiname: XPALProvider.idl
 * Projekt  : WollMux
 * Funktion : Interface-Definition für Lesezugriff auf die Persönliche Absenderliste (PAL)
 * 
 * Copyright (C) 2010 Landeshauptstadt München
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished
 * to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE. 
 *
 * @author Christoph Lutz (D-III-ITD 5.1)
 * 
 */

#ifndef __de_muenchen_allg_itd51_wollmux_XPALProvider_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XPALProvider_idl__ 
 
#include <com/sun/star/uno/XInterface.idl> 
  
module de {  module muenchen {  module allg { module itd51 { module wollmux {
 
/** 
  Das Interface XPALProvider stellt Methoden zum Auslesen der aktuellen
  Persönliche Absenderliste (PAL) zur Verfügung.
 */
interface XPALProvider
{
    /**
      Diese Methode liefert eine alphabethisch aufsteigend sortierte Liste mit
      String-Repräsentationen aller Einträge der Persönlichen Absenderliste (PAL)
      in einem String-Array. Die genaue Form der String-Repräsentationen wird
      von diesem Interface nicht vorgeschrieben, sondern ist im Falle des WollMux
      abhängig vom Wert von SENDER_DISPLAYTEMPLATE in der WollMux-Konfiguration.
      Unabhängig von SENDER_DISPLAYTEMPLATE enthalten die über diese Methode
      zurückgelieferten String-Repräsentationen der PAL-Einträge aber auf jeden
      Fall immer am Ende den String "§§%=%§§" gefolgt vom Schlüssel des
      entsprechenden Eintrags!
     */
	sequence< string > getPALEntries();

    /**
      Diese Methode liefert eine String-Repräsentation des aktuell aus der
      persönlichen Absenderliste (PAL) ausgewählten Absenders zurück.
      Die genaue Form der String-Repräsentation wird von diesem Interface nicht
      vorgeschrieben, sondern ist im Falle des WollMux abhängig vom Wert von
      SENDER_DISPLAYTEMPLATE in der WollMux-Konfiguration.
      Unabhängig von SENDER_DISPLAYTEMPLATE enthält die über diese Methode
      zurückgelieferte String-Repräsentation aber auf jeden Fall immer am Ende
      den String "§§%=%§§" gefolgt vom Schlüssel des aktuell ausgewählten
      Absenders.
      Ist die PAL leer oder noch kein Absender ausgewählt, so liefert die Methode
      den Leerstring "" zurück. Dieser Sonderfall sollte natürlich entsprechend
      durch die aufrufende Methode behandelt werden.
      
      @return den aktuell aus der PAL ausgewählten Absender als String. Ist kein
              Absender ausgewählt wird der Leerstring "" zurückgegeben.
     */
	string getCurrentSender();
};

}; }; }; }; };
 
#endif
