/*-
 * #%L
 * WollMux Interfaces
 * %%
 * Copyright (C) 2005 - 2020 Landeshauptstadt München
 * %%
 * Licensed under the EUPL, Version 1.1 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * http://ec.europa.eu/idabc/eupl5
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * #L%
 */
#ifndef __de_muenchen_allg_itd51_wollmux_XWollMux_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XWollMux_idl__ 

#include "XPALChangeEventBroadcaster.idl"
#include "XWollMuxDocument.idl"
#include <com/sun/star/document/XEventBroadcaster.idl>
#include <com/sun/star/text/XTextDocument.idl>
#include <com/sun/star/beans/PropertyValues.idl>
 
module de {  module muenchen {  module allg { module itd51 { module wollmux {

/**
  Dieses Interface beschreibt alle Methoden, die der WollMux-Service exportiert.
*/
interface XWollMux
{
    // Methoden zum Registrieren/Deregistieren von XPALChangeEventListenern.
    interface XPALChangeEventBroadcaster;

    /**
     * Die in diesem Interface beschriebenen Methoden registrieren bzw. deregistrieren
     * enstprechende Listener vom Typ XEventListener, über die der WollMux
     * über den Status der Dokumentbearbeitung informiert (z.B. wenn ein Dokument
     * vollständig bearbeitet/expandiert wurde). Die register-Methode ignoriert alle
     * XEventListenener-Instanzen, die bereits registriert wurden.
     * Mehrfachregistrierung der selben Instanz sind also nicht möglich.
     * 
     * Tritt ein entstprechendes Ereignis ein, so erfolgt der Aufruf der
     * entsprechenden Methoden XEventListener.notifyEvent(...) immer gleichzeitig
     * (d.h. für jeden Listener in einem eigenen Thread).
     * 
     * Der WollMux liefert derzeit folgende Events:
     * 
     * OnWollMuxProcessingFinished: Dieses Event wird erzeugt, wenn ein
     * Textdokument nach dem Öffnen vollständig vom WollMux bearbeitet und
     * expandiert wurde oder bei allen anderen Dokumenttypen direkt nach dem
     * Öffnen. D.h. für jedes in OOo geöffnete Dokument erfolgt früher oder später
     * ein solches Event. Wird ein neuer EventHandler registriert, so werden ihm
     * für alle bereits offenen OpenOffice.org Dokumente die 
     * OnWollMuxProcessingFinished Events nachgeliefert. Dies gilt auch für
     * unsichtbar in OOo geladene Dokumente mit Ausnahme von temporären Dokumenten
     * des OpenOffice.org-Seriendrucks (die beim Seriendruck massenweise für jeden
     * Datensatz angelegt werden) oder von temporären Dokumenten, die für die 
     * Einfügung von Autotexten im Hintergrund erzeugt werden. Solche Dokumente 
     * werden durch den WollMux nicht verarbeitet. 
     */	
    interface com::sun::star::document::XEventBroadcaster;

    /**
      Diese Methode setzt den aktuellen Absender der Persönlichen Absenderliste
      (PAL) auf den Absender sender. Der Absender wird nur gesetzt, wenn die
      Parameter sender und idx in der alphabetisch sortierten Absenderliste des
      WollMux übereinstimmen - d.h. die Absenderliste der veranlassenden
      SenderBox zum Zeitpunkt der Auswahl konsistent zur PAL des WollMux war. 
      Die Methode verwendet für sender das selben Format wie es vom
      XPALProvider:getCurrentSender() geliefert wird.
     */
    void setCurrentSender([in] string sender, [in] short index);

    /**
      Liefert die zum aktuellen Zeitpunkt im WollMux ausgewählten Absenderdaten (die
      über das Dokumentkommandos WM(CMD'insertValue' DB_SPALTE'<dbSpalte>') in ein
      Dokument eingefügt würden) in einem Array von PropertyValue-Objekten
      zurück. Dabei repräsentieren die Attribute PropertyValue.Name die
      verfügbaren DB_SPALTEn und die Attribute PropertyValue.Value die zu
      DB_SPALTE zugehörigen Absenderdaten.
    
      Jeder Aufruf erzeugt ein komplett neues und unabhängiges Objekt mit allen
      Einträgen die zu dem Zeitpunkt gültig sind. Eine Änderung der Werte des
      Rückgabeobjekts hat daher keine Auswirkung auf den WollMux.
    
      @return Array von PropertyValue-Objekten mit den aktuell im WollMux gesetzten
              Absenderdaten. Gibt es keine Absenderdaten, so ist das Array leer (aber
              != null).
     */
    com::sun::star::beans::PropertyValues getInsertValues();

    /**
      Diese Methode liefert den Wert der Absenderdaten zur Datenbankspalte dbSpalte,
      der dem Wert entspricht, den das Dokumentkommando WM(CMD'insertValue'
      DB_SPALTE'<dbSpalte>') in das Dokument einfügen würde, oder den Leerstring ""
      wenn dieser Wert nicht bestimmt werden kann (z.B. wenn ein ungültiger
      Spaltennamen dbSpalte übergeben wurde).
    
      Anmerkung: Diese Methode wird durch die Methode getInsertValues() ergänzt die
      alle Spaltennamen und Spaltenwerte zurück liefern kann.
    
      @param dbSpalte
               Name der Datenbankspalte deren Wert zurückgeliefert werden soll.
      @return Der Wert der Datenbankspalte dbSpalte des aktuell ausgewählten Absenders
              oder "", wenn der Wert nicht bestimmt werden kann.
     */	
    string getValue([in] string dbSpalte);

    /**
      Macht das selbe wie XWollMuxDocument wdoc = getWollMuxDocument(doc); if (wdoc !=
      null) wdoc.addPrintFunction(functionName) und sollte durch diese Anweisungen
      entsprechend ersetzt werden.
       
      @param doc
               Das Dokument, dem die Druckfunktion functionName hinzugefügt werden
               soll.
      @param functionName
               der Name einer Druckfunktion, die im Abschnitt "Druckfunktionen" der
               WollMux-Konfiguration definiert sein muss.
      @deprecated since 2009-09-18
     */
    void addPrintFunction([in] com::sun::star::text::XTextDocument doc, [in] string functionName);

    /**
      Macht das selbe wie XWollMuxDocument wdoc = getWollMuxDocument(doc); if (wdoc !=
      null) wdoc.removePrintFunction(functionName) und sollte durch diese Anweisungen
      entsprechend ersetzt werden.
      
      @param doc
               Das Dokument, dem die Druckfunktion functionName genommen werden soll.
      @param functionName
               der Name einer Druckfunktion, die im Dokument gesetzt ist.
      @deprecated since 2009-09-18
     */
    void removePrintFunction([in] com::sun::star::text::XTextDocument doc, [in] string functionName);
        
    /**
      Ermöglicht den Zugriff auf WollMux-Funktionen, die spezifisch für das Dokument
      doc sind. Derzeit ist als doc nur ein c.s.s.t.TextDocument möglich. Wird ein
      Dokument übergeben, für das der WollMux keine Funktionen anbietet (derzeit zum
      Beispiel ein Calc-Dokument), so wird null zurückgeliefert. Dass diese Funktion
      ein nicht-null Objekt zurückliefert bedeutet jedoch nicht zwangsweise, dass der
      WollMux für das Dokument sinnvolle Funktionen bereitstellt. Es ist möglich, dass
      Aufrufe der entsprechenden Funktionen des XWollMuxDocument-Interfaces nichts
      tun.
      
      Hinweis zur Synchronisation: Aufrufe der Funktionen von XWollMuxDocument können
      ohne weitere Synchronisation sofort erfolgen. Jedoch ersetzt
      getWollMuxDocument() keinesfalls die Synchronisation mit dem WollMux.
      Insbesondere ist es möglich, dass getWollMuxDocument() zurückkehrt BEVOR der
      WollMux das Dokument doc bearbeitet hat. Vergleiche hierzu die Beschreibung von
      XWollMuxDocument.
      
      @param doc
               Ein OpenOffice.org-Dokument, in dem dokumentspezifische Funktionen des
               WollMux aufgerufen werden sollen.
      @return Liefert null, falls doc durch den WollMux nicht bearbeitet wird und eine
              Instanz von XWollMuxDocument, falls es sich bei doc prinzipiell um ein
              WollMux-Dokument handelt.
     */
    XWollMuxDocument getWollMuxDocument([in] com::sun::star::lang::XComponent doc);
    
}; 
  
service WollMux: XWollMux;

}; }; }; }; };
 
#endif
