/*-
 * #%L
 * WollMux
 * %%
 * Copyright (C) 2005 - 2023 Landeshauptstadt München and LibreOffice contributors
 * %%
 * Licensed under the EUPL, Version 1.1 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * http://ec.europa.eu/idabc/eupl5
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * #L%
 */
package org.libreoffice.lots.config.scanner;

import java.util.regex.Pattern;

/**
 * Different types of tokens which can be generated by the scanner.
 *
 * @author Daniel Sikeler
 */
public enum TokenType
{
  /** Token representing whitespace. */
  WHITESPACE("\\A[,;\\s]+"),
  /** Token representing a key. */
  KEY("\\A^[a-zA-Z_][a-zA-Z_0-9]*"),
  /** Token representing a value. */
  VALUE("\\A((\\\'(\\\'\\\'|[^\\\'])*\\\')|(\\\"(\\\"\\\"|[^\\\"])*\\\"))"),
  /** Token representing a open bracket. */
  OPENING_BRACKET("\\A\\("),
  /** Token representing a closing bracket. */
  CLOSING_BRACKET("\\A\\)"),
  /** Token representing a comment. */
  COMMENT("\\A#.*\\z"),
  /** Token representing the beginning of a new file. */
  NEW_FILE("\\A%include \\\".*\\\".*"),
  /** Token representing the end of a file. */
  END_FILE("");

  /**
   * A regular expression for this type, or null if there is no regular
   * expression.
   */
  private final Pattern regex;

  /**
   * Constructor for token types.
   *
   * @param regex
   *          String-representation of the regular expression, or empty String
   *          if there doesn't exist a regular expression.
   */
  TokenType(final String regex)
  {
    if (regex.isEmpty())
    {
      this.regex = null;
    } else
    {
      this.regex = Pattern.compile(regex, Pattern.UNICODE_CASE);
    }
  }

  public Pattern getRegex()
  {
    return regex;
  }

  /**
   * Is there a regular expression for this token type.
   *
   * @return true if an regular expression exist, false otherwise.
   */
  public boolean hasRegex()
  {
    return regex != null;
  }
}
