oxt/*.xcu /opt/libreoffice4.1/share/extensions/wollmux/
oxt/*.rdb /opt/libreoffice4.1/share/extensions/wollmux/
oxt/META-INF/manifest.xml /opt/libreoffice4.1/share/extensions/wollmux/META-INF/
oxt/help/component*.txt /opt/libreoffice4.1/share/extensions/wollmux/help/
oxt/description.xml /opt/libreoffice4.1/share/extensions/wollmux/
thirdparty /opt/libreoffice4.1/share/extensions/wollmux/
misc/buildinfo /opt/libreoffice4.1/share/extensions/wollmux/
basic/ /opt/libreoffice4.1/share/extensions/wollmux/
