/*
 * Dateiname: XPALChangeEventBroadcaster.idl
 * Projekt  : WollMux
 * Funktion : Interface-Definition für einen Broadcaster von Änderungen an der Persönliche Absenderliste (PAL)
 * 
 * Copyright (c) 2008 Landeshauptstadt München
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the European Union Public Licence (EUPL),
 * version 1.0.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * European Union Public Licence for more details.
 *
 * You should have received a copy of the European Union Public Licence
 * along with this program. If not, see
 * http://ec.europa.eu/idabc/en/document/7330
 *
 * @author Christoph Lutz (D-III-ITD 5.1)
 * @version 1.0
 * 
 */

#ifndef __de_muenchen_allg_itd51_wollmux_XPALChangeEventBroadcaster_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XPALChangeEventBroadcaster_idl__ 
 
#include "XPALChangeEventListener.idl" 
 
module de {  module muenchen {  module allg { module itd51 { module wollmux {

/** 
  Das Interface XPALChangeEventBroadcasteristener definiert einen Broadcaster, der über
  Änderungen an der Persönlichen Absenderliste (PAL) informieren kann. Er enthält
  Methoden zum Registrieren und Deregistrieren von XPALChangeEventListenern.
 */ 
interface XPALChangeEventBroadcaster
{
    /**
      Diese Methode registriert einen XPALChangeEventListener, der updates
      empfängt wenn sich die PAL ändert. Nach dem Registrieren wird sofort ein
      ON_SELECTION_CHANGED Ereignis ausgelöst, welches dafür sort, dass sofort
      ein erster update aller Listener ausgeführt wird. Die Methode ignoriert
      alle XPALChangeEventListenener-Instanzen, die bereits registriert wurden.
      Mehrfachregistrierung der selben Instanz ist also nicht möglich.
     */
	void addPALChangeEventListener( [in] XPALChangeEventListener listener);

    /**
      Diese Methode registriert einen XPALChangeEventListener, der updates
      empfängt wenn sich die PAL ändert; nach der Registrierung wird geprüft, ob
      der WollMux und der XPALChangeEventListener die selbe WollMux-Konfiguration
      verwenden, wozu der Listener den HashCode wollmuxConfHashCode der aktuellen
      WollMux-Konfiguration übermittelt. Stimmt wollmuxConfHashCode nicht mit dem
      HashCode der WollMux-Konfiguration des WollMux überein, so erscheint ein
      Dialog, der vor möglichen Fehlern warnt. Nach dem Registrieren wird sofort
      ein ON_SELECTION_CHANGED Ereignis ausgelöst, welches dafür sort, dass
      sofort ein erster update aller Listener ausgeführt wird. Die Methode
      ignoriert alle XPALChangeEventListenener-Instanzen, die bereits registriert
      wurden. Mehrfachregistrierung der selben Instanz ist also nicht möglich.
      
      @param l
               Der zu registrierende XPALChangeEventListener
      @param wollmuxConfHashCode
               Der HashCode der WollMux-Config der zur Konsistenzprüfung
               herangezogen wird und über
               WollMuxFiles.getWollMuxConf().getStringRepresentation().hashCode()
               erzeugt wird.
     */
	void addPALChangeEventListenerWithConsistencyCheck( [in] XPALChangeEventListener listener, [in] long wollmuxConfHashCode);

    /**
      Diese Methode deregistriert einen XPALChangeEventListener wenn er bereits
      registriert war.
     */
	void removePALChangeEventListener( [in] XPALChangeEventListener listener);
};

}; }; }; }; };
 
#endif
