/*
 * Dateiname: XPALChangeEventListener.idl
 * Projekt  : WollMux
 * Funktion : Interface-Definition für einen Listener auf Änderungen an der Persönliche Absenderliste (PAL)
 * 
 * Copyright (c) 2008 Landeshauptstadt München
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the European Union Public Licence (EUPL),
 * version 1.0.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * European Union Public Licence for more details.
 *
 * You should have received a copy of the European Union Public Licence
 * along with this program. If not, see
 * http://ec.europa.eu/idabc/en/document/7330/5980
 *
 * @author Christoph Lutz (D-III-ITD 5.1)
 * @version 1.0
 * 
 */

#ifndef __de_muenchen_allg_itd51_wollmux_XPALChangeEventListener_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XPALChangeEventListener_idl__ 
 
#include <com/sun/star/lang/XEventListener.idl> 
#include <com/sun/star/lang/EventObject.idl> 
#include <com/sun/star/frame/XFrame.idl> 
  
module de {  module muenchen {  module allg { module itd51 { module wollmux {
 
/** 
  Das Interface XPALChangeEventListener definiert einen Listener, der Änderungen an der
  Persönlichen Absenderliste (PAL) behandeln kann. 
  
  Siehe auch XPALChangeEventBroadcaster, in dem der Listener registriert werden kann.
 */
interface XPALChangeEventListener 
{
    // Ableitung vom Standard-XEventListener
    interface com::sun::star::lang::XEventListener;
    
    /**
      Die Methode wird wird bei jeder Änderung (hinzufügen und entfernen von Einträgen oder
      wenn ein neuer Absender gesetzt wurde) an der Persölichen Absenderliste aufgerufen. 
      Das eventObject.Source enthält den XPALProvider, dessen PAL sich geändert hat. Der 
      übergebene XPALProvider kann verwendet werden, um die Absenderliste neu aufzubauen.
     */
	void updateContent( [in] com::sun::star::lang::EventObject eventObject );
};

}; }; }; }; };
 
#endif
