/*
 * Dateiname: XPrintModel.idl
 * Projekt  : WollMux
 * Funktion : Repräsentiert die Schnittstelle WollMux Komfortdruckfunktionen
 * 
 * Copyright: Landeshauptstadt München
 *
 * @author Christoph Lutz (D-III-ITD 5.1)
 * @version 1.0
 * 
 */

#ifndef __de_muenchen_allg_itd51_wollmux_XPrintModel_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XPrintModel_idl__ 
 
#include <com/sun/star/uno/XInterface.idl> 
#include <com/sun/star/text/XTextDocument.idl> 
#include <com/sun/star/beans/XPropertySet.idl>
#include <com/sun/star/beans/PropertyValue.idl>
  
module de {  module muenchen {  module allg { module itd51 { module wollmux {
 
/** 
  Jeder Druckfunktion wird beim Aufruf ein XPrintModel-Objekt übergeben, über
  das der Zugriff auf das Dokument und Komfortmethoden für den Druck zur 
  Verfuegung stehen. Verschiedene Druckfunktionen können dabei zu einer 
  Aufrufkette zusammengefügt sein.
 */
interface XPrintModel
{

    /**
     * Jede Druckfunktion kann über dieses Interface funktionsspezifische 
     * Properties im XPrintModel setzen, die von anderen Druckfunktionen in der
     * Aufrufkette des XPrintModels ausgewertet werden können.
     */
	interface com::sun::star::beans::XPropertySet;
	
    /**
     * Liefert das XTextDocument mit dem die Druckfunktion aufgerufen wurde.
     */
    com::sun::star::text::XTextDocument getTextDocument();

    /**
     * Deprecated: Bitte benutzen Sie statt dieser Methode die Methode
     * printWithProps() mit dem entsprechend gesetzten Property "CopyCount".
     * Diese Methode dient nur der Abwärtskompatibilität mit älteren
     * XPrintModels und verwendet intern ebenfalls die Methode printWithProps()
     * und der Property "CopyCount".
     */
    void print( [in] short numberOfCopies);

    /**
     * Druckt das TextDocument auf dem aktuell eingestellten Drucker aus oder
     * leitet die Anfrage an die nächste verfügbare Druckfunktion in der
     * Aufrufkette weiter, wenn eine weitere Druckfunktion vorhanden ist;
     * Abhängig von der gesetzten Druckfunktion werden dabei verschiedene
     * Properties, die über setPropertyValue(...) gesetzt wurden.
     */
    void printWithProps();
	
    /**
     * Zeigt den PrintSetupDialog an, über den der aktuelle Drucker ausgewählt
     * und geändert werden kann.
     * 
     * @param onlyOnce
     *          Gibt an, dass der Dialog nur beim ersten Aufruf (aus Sicht eines
     *          Dokuments) der Methode angezeigt wird. Wurde bereits vor dem
     *          Aufruf ein PrintSetup-Dialog gestartet, so öffnet sich der
     *          Dialog nicht und die Methode endet ohne Aktion.
     */
    void showPrinterSetupDialog( [in] boolean onlyOnce);
		
    /**
     * Falls es sich bei dem zugehörigen Dokument um ein Formulardokument (mit
     * einer Formularbeschreibung) handelt, wird das Formularfeld mit der ID id
     * auf den neuen Wert value gesetzt und alle von diesem Formularfeld
     * abhängigen Formularfelder entsprechend angepasst. Handelt es sich beim
     * zugehörigen Dokument um ein Dokument ohne Formularbeschreibung, so werden
     * nur alle insertFormValue-Kommandos dieses Dokuments angepasst, die die ID
     * id besitzen.
     * 
     * @param id
     *          Die ID des Formularfeldes, dessen Wert verändert werden soll.
     *          Ist die FormGUI aktiv, so werden auch alle von id abhängigen
     *          Formularwerte neu gesetzt.
     * @param value
     *          Der neue Wert des Formularfeldes id
     */
    void setFormValue( [in] string id, [in] string value);

    /**
     * Liefert true, wenn das Dokument als "modifiziert" markiert ist und damit
     * z.B. die "Speichern?" Abfrage vor dem Schließen erscheint.
     * 
     * Manche Druckfunktionen verändern u.U. den Inhalt von Dokumenten. Trotzdem
     * kann es sein, dass eine solche Druckfunktion den "Modifiziert"-Status des
     * Dokuments nicht verändern darf um ungewünschte "Speichern?"-Abfragen zu
     * verhindern. In diesem Fall kann der "Modifiziert"-Status mit folgendem
     * Konstrukt innerhalb der Druckfunktion unverändert gehalten werden:
     * 
     * boolean modified = pmod.getDocumentModified();
     * 
     * ...die eigentliche Druckfunktion, die das Dokument verändert...
     * 
     * pmod.setDocumentModified(modified);
     */
    boolean getDocumentModified();

    /**
     * Diese Methode setzt den DocumentModified-Status auf modified.
     */
    void setDocumentModified( [in] boolean modified);
	
    /**
     * Sammelt alle Formularfelder des Dokuments auf, die nicht von
     * WollMux-Kommandos umgeben sind, jedoch trotzdem vom WollMux verstanden
     * und befüllt werden (derzeit c,s,s,t,textfield,Database-Felder). So werden
     * z.B. Seriendruckfelder erkannt, die erst nach dem Öffnen des Dokuments
     * manuell hinzugefügt wurden.
     */
    void collectNonWollMuxFormFields();
    
    /**
     * Lädt die in der wollmux.conf definierte Druckfunktion mit dem Namen
     * functionName in das XPrintModel und ordnet sie gemäß dem ORDER-Attribut
     * an der richtigen Position in die Aufrufkette der zu bearbeitenden
     * Druckfunktionen ein; Die Druckfunktion wird im Fall des Aufrufs ohne ein
     * zusätzliches Argument gestartet. Sie wird nicht nochmal in die
     * Aufrufkette eingefügt, wenn bereits eine Druckfunktion mit dem selben
     * Namen im XPrintModel vorhanden ist.
     * 
     * @param functionName
     *          Name der Druckfunktion, die durch das MasterPrintModel verwaltet
     *          und ohne Argumente aufgerufen werden soll.
     * @return liefert true, wenn die Druckfunktion erfolgreich in die
     *         Aufrufkette übernommen wurde oder bereits geladen war und false,
     *         wenn die Druckfunktion aufgrund vorangegangener Fehler nicht in
     *         die Aufrufkette aufgenommen werden konnte.
     */
    boolean usePrintFunction([in] string functionName);

    /**
     * Lädt die in der wollmux.conf definierte Druckfunktion mit dem Namen
     * functionName in das XPrintModel und ordnet sie gemäß dem ORDER-Attribut
     * an der richtigen Position in die Aufrufkette der zu bearbeitenden
     * Druckfunktionen ein; Die Druckfunktion wird im Fall des Aufrufs mit dem
     * zusätzlichen Argument arg gestartet. Sie wird nicht nochmal in die
     * Aufrufkette eingefügt, wenn bereits eine Druckfunktion mit dem selben
     * Namen im XPrintModel vorhanden ist, das Argument arg wird aber in jedem
     * Fall übernommen.
     * 
     * @param functionName
     *          Name der Druckfunktion, die durch das MasterPrintModel verwaltet
     *          und mit dem Argument arg aufgerufen werden soll.
     * @param arg
     *          Das Argument das der Druckfunktion beim Aufruf übergeben wird.
     * @return liefert true, wenn die Druckfunktion erfolgreich in die
     *         Aufrufkette übernommen wurde oder bereits geladen war und false,
     *         wenn die Druckfunktion aufgrund vorangegangener Fehler nicht in
     *         die Aufrufkette aufgenommen werden konnte.
     */
    boolean usePrintFunctionWithArgument([in] string functionName, [in] any arg);

    /**
     * Lädt die WollMux-interne Druckfunktion printFunction (muss als
     * PrintFunction-Objekt vorliegen) in das XPrintModel und ordnet sie gemäß
     * dem ORDER-Attribut an der richtigen Position in die Aufrufkette der zu
     * bearbeitenden Druckfunktionen ein; Die Druckfunktion wird im Fall des
     * Aufrufs ohne ein zusätzliches Argument gestartet. Sie wird nicht nochmal
     * in die Aufrufkette eingefügt, wenn bereits eine Druckfunktion mit dem
     * selben Namen im XPrintModel vorhanden ist.
     * 
     * @param functionName
     *          Name der Druckfunktion, die durch das MasterPrintModel verwaltet
     *          und ohne Argumente aufgerufen werden soll.
     * @return liefert true, wenn die Druckfunktion erfolgreich in die
     *         Aufrufkette übernommen wurde oder bereits geladen war und false,
     *         wenn die Druckfunktion aufgrund vorangegangener Fehler nicht in
     *         die Aufrufkette aufgenommen werden konnte.
     */
    boolean useInternalPrintFunction([in] any printFunction);

    /**
     * Lädt die WollMux-interne Druckfunktion printFunction (muss als
     * PrintFunction-Objekt vorliegen) in das XPrintModel und ordnet sie gemäß
     * dem ORDER-Attribut an der richtigen Position in die Aufrufkette der zu
     * bearbeitenden Druckfunktionen ein; Die Druckfunktion wird im Fall des
     * Aufrufs mit dem zusätzlichen Argument arg gestartet. Sie wird nicht
     * nochmal in die Aufrufkette eingefügt, wenn bereits eine Druckfunktion mit
     * dem selben Namen im XPrintModel vorhanden ist, das Argument arg wird aber
     * in jedem Fall übernommen.
     * 
     * @param functionName
     *          Name der Druckfunktion, die durch das MasterPrintModel verwaltet
     *          und mit dem Argument arg aufgerufen werden soll.
     * @param arg
     *          Das Argument das der Druckfunktion beim Aufruf übergeben wird.
     * @return liefert true, wenn die Druckfunktion erfolgreich in die
     *         Aufrufkette übernommen wurde oder bereits geladen war und false,
     *         wenn die Druckfunktion aufgrund vorangegangener Fehler nicht in
     *         die Aufrufkette aufgenommen werden konnte.
     * 
     * @author Christoph Lutz (D-III-ITD-5.1)
     */
    boolean useInternalPrintFunctionWithArgument([in] any printFunction, [in] any arg);

    /**
     * Diese Methode setzt neue Eigenschaften für die Druckblöcke (z.B.
     * allVersions), die in properties spezifiziert sind, und speichert die
     * ursprünglichen Eigenschaften der Druckblölcke in einer internen HashMap
     * unter dem Schlüssel key ab. Mit Hilfe von restorePrintBlocksProps(key)
     * können die ürsprünglichen Einstellungen später wieder hergestellt werden.
     * 
     * @param key
     *          Ein belibiges Objekt das als Schlüssel verwendet wird, um mit
     *          Hilfe von restorePrintBlocksProps(key) die Einstellungen wieder
     *          herstellen zu können, die vor dem Aufruf dieser Methode gesetzt
     *          waren.
     * @param properties
     *          Array von PropertyValue-Objekten. Folgende Properties werden
     *          dabei von dieser Methode ausgewertet wenn sie angegeben sind:
     *          Das Property "NotInOriginalVisible" (Boolean) ermöglicht das
     *          Anzeigen/Ausblenden der NotInOriginal-Druckblöcke. Das Property
     *          "DraftOnlyVisible" (Boolean) ermöglicht das Anzeigen/Ausblenden
     *          der DraftOnly-Druckblöcke. Das Property "AllVersionsVisible"
     *          (Boolean) ermöglicht das Anzeigen/Ausblenden der
     *          allVersions-Druckblöcke. Ist "HideHighlightColor" (Boolean) ==
     *          True, so werden all Hintergrundfarben der über die Properties
     *          "*Visible" angesprochenen Druckblöcke auf den
     *          Standardhintergrund zurückgesetzt.
     */
	void setPrintBlocksProps([in] any key, [in] sequence<com::sun::star::beans::PropertyValue> props);

    /**
     * Diese Methode ermöglicht, gesteuert über den Schlüssel key, das
     * Wiederherstellen der Eigenschaften der Druckblöcke, die vor dem Aufruf
     * von setPrintBlocksProperties(key, props) gesetzt waren.
     * 
     * @param key
     *          Der Key ist ein belibiges Objekt, das intern als Schlüssel für
     *          eine HashMap verwendet wird, in der die ursprünglichen Zustände
     *          der Druckblöcke abgelegt wurden. Nach dem Durchlauf dieser
     *          Methode wird der Schlüssel key aus der internen HashMap
     *          entfernt.
     */
	void restorePrintBlocksProps([in] any key);
};

}; }; }; }; };
 
#endif
