/*
 * Dateiname: XSenderBox.idl
 * Projekt  : WollMux
 * Funktion : Implementierung eines com.sun.star.frame.ToolbarController
              als ComboBox zur Auswahl des aktuellen Absenders
 * 
 * Copyright: Landeshauptstadt M?nchen
 *
 * ?nderungshistorie:
 * Nr. |  Datum     |   Autor   | ?nderungsgrund
 * -------------------------------------------------------------------
 * 001 | 13.09.2005 |    LUT    | Erstellung
 * -------------------------------------------------------------------
 *
 * @author D-HAIII 5.1 Christoph Lutz
 * @version 1.0
 * 
 */
#ifndef __de_muenchen_allg_itd51_wollmux_XSenderBox_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XSenderBox_idl__ 
 
#include <com/sun/star/frame/XStatusListener.idl> 
#include <com/sun/star/lang/XInitialization.idl> 
#include <com/sun/star/util/XUpdatable.idl> 
#include <com/sun/star/frame/XToolbarController.idl> 
#include <com/sun/star/frame/XFrame.idl> 
 
//============================================================================= 
 
 module de {  module muenchen {  module allg { module itd51 { module wollmux {
 
//============================================================================= 
 
/** Das new-style Interface XSenderBox beschreibt die Eigenschaften des 
    com.sun.star.frame.ToolbarController-Service.
 */
interface XSenderBox
{
	interface com::sun::star::frame::XStatusListener;
    interface com::sun::star::lang::XInitialization;
    interface com::sun::star::util::XUpdatable;
    interface com::sun::star::frame::XToolbarController;

	void updateContent();
	void updateContentForFrame([in] com::sun::star::frame::XFrame xFrame);
}; 
 
//============================================================================= 
 
service SenderBox: XSenderBox;

}; }; }; }; };
 
/*============================================================================= 
 
=============================================================================*/ 
#endif
