/*
 * Dateiname: XWollMux.idl
 * Projekt  : WollMux
 * Funktion : Interface-Definition für den WollMux-Service
 * 
 * Copyright: Landeshauptstadt München
 *
 * @author Christoph Lutz (D-III-ITD 5.1)
 * @version 1.0
 * 
 */
 
#ifndef __de_muenchen_allg_itd51_wollmux_XWollMux_idl__ 
#define __de_muenchen_allg_itd51_wollmux_XWollMux_idl__ 

#include "XPALChangeEventBroadcaster.idl"
#include <com/sun/star/document/XEventBroadcaster.idl>
 
module de {  module muenchen {  module allg { module itd51 { module wollmux {

/**
  Dieses Interface beschreibt alle Methoden, die der WollMux-Service exportiert.
*/
interface XWollMux
{
	// Methoden zum Registrieren/Deregistieren von XPALChangeEventListenern.
	interface XPALChangeEventBroadcaster;

    /**
     * Die in diesem Interface beschriebenen Methoden registrieren bzw. deregistrieren
     * enstprechende Listener vom Typ XEventListener, über die der WollMux
     * über den Status der Dokumentbearbeitung informiert (z.B. wenn ein Dokument
     * vollständig bearbeitet/expandiert wurde). Die register-Methode ignoriert alle
     * XEventListenener-Instanzen, die bereits registriert wurden.
     * Mehrfachregistrierung der selben Instanz sind also nicht möglich.
     * 
     * Tritt ein entstprechendes Ereignis ein, so erfolgt der Aufruf der
     * entsprechenden Methoden XEventListener.notifyEvent(...) immer gleichzeitig
     * (d.h. für jeden Listener in einem eigenen Thread).
     * 
     * Der WollMux liefert derzeit folgende Events:
     * 
     * OnWollMuxProcessingFinished: Dieses Event wird erzeugt, wenn ein
     * Textdokument nach dem Öffnen vollständig vom WollMux bearbeitet und
     * expandiert wurde oder bei allen anderen Dokumenttypen direkt nach dem
     * Öffnen. D.h. für jedes in OOo geöffnete Dokument erfolgt früher oder später
     * ein solches Event.
     */	
	interface com::sun::star::document::XEventBroadcaster;

    /**
      Diese Methode setzt den aktuellen Absender der Persönlichen Absenderliste
      (PAL) auf den Absender sender. Der Absender wird nur gesetzt, wenn die
      Parameter sender und idx in der alphabetisch sortierten Absenderliste des
      WollMux übereinstimmen - d.h. die Absenderliste der veranlassenden
      SenderBox zum Zeitpunkt der Auswahl konsistent zur PAL des WollMux war. 
      Die Methode verwendet für sender das selben Format wie es vom
      XPALProvider:getCurrentSender() geliefert wird.
     */
	void setCurrentSender([in] string sender, [in] short index);

    /**
      Diese Methode liefert den Wert zur Datenbankspalte dbSpalte, der dem Wert
      entspricht, den das Dokumentkommando WM(CMD'insertValue' DB_SPALTE'<dbSpalte>')
      in das Dokument einfügen würde, oder den Leerstring "" wenn dieser Wert
      nicht bestimmt werden kann (z.B. wenn ein ungültiger Spaltennamen dbSpalte
      übergeben wurde). So ist es z.B. möglich, aus externen Anwendungen (z.B.
      Basic-Makros) auf Werte des aktuell gesetzten Absenders des WollMux
      zuzugreifen.
    
      Anmerkung: Ist die aufrufende Anwendung ein Basic-Makro, so muss damit
      gerechnet werden, dass dieses Makro bereits in einer synchronisierten
      Umgebung abläuft (das ist Standard bei Basic-Makros). Um Deadlocks in
      Zusammenhang mit dem WollMux zu vermeiden, darf die Methode also nicht über
      den WollMuxEventHandler synchonisiert werden. Aufgrund der fehlenden
      Synchronisierung auf Seiten des WollMux ist die Methode jedoch mit Vorsicht
      zu genießen. Insbesondere sollten die über diese Methode gelieferten Werte
      NICHT verwendet werden, um z.B. mit setCurrentSender() Daten des WollMux zu
      manipulieren.
    
      Zum Auslesen und Reagieren auf Änderungen der PersoenlichenAbsenderlist
      (PAL) sollten die Methoden verwendet werden, die der XPALProvider anbietet.
      Diese Methoden sind über den WollMuxEventHandler synchronisiert.
    
      @param dbSpalte
               Name der Datenbankspalte deren Wert zurückgeliefert werden soll.
      @return Der Wert der Datenbankspalte dbSpalte des aktuell ausgewählten
              Absenders oder "", wenn der Wert nicht bestimmt werden kann.
     */	
    string getValue([in] string dbSpalte);
}; 
  
service WollMux: XWollMux;

}; }; }; }; };
 
#endif
